### ISSUE TITLE
How to get Cake\Database\Exception sent to Sentry ?

### ISSUE THREAD

**Issue by jeremyhalin** [josegonzalez/php-error-handlers#20]
In logs I have these kind of Exception, but they are not sent to Sentry.

```
2018-03-23 12:49:11 Error: [Cake\Database\Exception] SQLSTATE[42S02]: Base table or view not found:
```

How can I config php-error-handlers so it catch also Database\Exception ?

Thanks.

**Comment by josegonzalez** [comment]
Can you gist your error handler setup? All errors _should_ be sent over.

If you can get me a way to duplicate this, that would be a+.

**Comment by jeremyhalin** [comment]
@josegonzalez Sorry for the late answer, here is my error handler setup :


```php
    $isCli = PHP_SAPI === 'cli';
    if (IS_PROD || IS_DEV) {
        if ($isCli) {
            (new \Josegonzalez\ErrorHandlers\Cake\ConsoleErrorHandler(Configure::read('Error')))->register();
        } else {
            (new \Josegonzalez\ErrorHandlers\Cake\ErrorHandler(Configure::read('Error')))->register();
        }
    } else {
        if ($isCli) {
            (new ConsoleErrorHandler(Configure::read('Error')))->register();
        } else {
            (new ErrorHandler(Configure::read('Error')))->register();
        }
    }


    if (IS_PROD || IS_DEV) {
        Plugin::load('Josegonzalez/ErrorHandlers', ['path' => ROOT . DS . 'vendor' . 'DS' . 'josegonzalez' . DS . 'php-error-handlers' . DS . 'src', 'autoload' => true]);

        // Create an array of configuration data to pass to the handler class

        $config = [
            'handlers' => [
                'Josegonzalez\ErrorHandlers\Handler\SentryHandler' => [
                    'dsn' => 'https://*************'
                ],
            ],
        ];

        // Register the error handler
        (new \Josegonzalez\ErrorHandlers\Handler($config))->register();
    }
```

Maybe it's duplicate content ?

**Comment by jeremyhalin** [comment]
@josegonzalez Did you find something ?

**Comment by josegonzalez** [comment]
Sorry, haven't had any chance to look at this recently.

Why are you configuring the handler twice? I think thats screwing it up. Please set it up _exactly_ as I show it in the docs.

If you wish to disable the handler for staging, simply set `$config` to empty when you're in staging.

**Comment by jeremyhalin** [comment]
Thanks, so I cleaned up my bootstrap file, here is what I got:
```php
/*
 * Register application error and exception handlers.
 */
$isCli = PHP_SAPI === 'cli';
if ($isCli) {
    (new ConsoleErrorHandler(Configure::read('Error')))->register();
} else {
    (new ErrorHandler(Configure::read('Error')))->register();
}

/*
 * Register application error and exception handlers in production (Sentry).
 */
if (IS_PROD || IS_DEV || IS_LOCALHOST /* for testing purpose */) {
    // Plugin::load('Josegonzalez/ErrorHandlers', ['path' => ROOT . DS . 'vendor' . 'DS' . 'josegonzalez' . DS . 'php-error-handlers' . DS . 'src', 'autoload' => true]);

    // Create an array of configuration data to pass to the handler class
    $config = [
        'handlers' => [
            'Josegonzalez\ErrorHandlers\Handler\SentryHandler' => [
                'dsn' => 'https://*****************@sentry.io/******'
            ],
        ],
    ];

    // Register the error handler
    (new \Josegonzalez\ErrorHandlers\Handler($config))->register();
}
```

It's working fine, but I got a little problem. All database exceptions are not catch.
Here is an example:
![image](https://user-images.githubusercontent.com/6832672/39864568-52c62822-544a-11e8-9511-879c71c849d2.png)
In this case, I renamed my column in database `username` to `usernamee`.

In Sentry, error doesn't show up:
![image](https://user-images.githubusercontent.com/6832672/39864665-a0cd6a30-544a-11e8-98e6-b16f79fc013d.png)

**Comment by josegonzalez** [comment]
Okay, I'll try and investigate this with a fresh app sometime today/tomorrow

**Comment by JeremyWinalist** [comment]
@josegonzalez hi, did you find time to investigate ?

**Comment by JeremyWinalist** [comment]
> Okay, I'll try and investigate this with a fresh app sometime today/tomorrow

Hi @josegonzalez
Any news ?
